apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: local
spec:
  config:
    client_mode: service
    enable: true
    mode: monitor
  rules:
  - action: allow
    comment: Allow deployments in system namespaces.
    criteria:
    - name: namespace
      op: containsAny
      value: kube-system,kube-public,istio-system
    disabled: true
    id: 1
  - action: allow
    comment: Allow deployments in NeuVector namespace
    criteria:
    - name: namespace
      op: containsAny
      value: neuvector
    disabled: true
    id: 2
  - action: deny
    comment: my-security-rule
    criteria:
    - name: labels
      op: notContainsAny
      path: labels
      value: de.alfter-web
    id: 1000
