---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-write
rules:
- apiGroups:
  - ""  # "" indicates the core API group
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-write
subjects:
- kind: Group
  name: clusterusers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-write
  apiGroup: rbac.authorization.k8s.io
