---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-cm
data:
  background.color: darkgreen
  #background.color: darkblue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image:  registry.gitlab.com/malfter/demo-app:latest
          imagePullPolicy: Always
          env:
            - name: DEMO_APP_BACKGROUND_COLOR
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: demo-app-cm
                  # Specify the key associated with the value
                  key: background.color
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "250m"
              memory: "300Mi"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  selector:
    app: demo-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapp-ingress
spec:
  rules:
  - host: demo-app.{{MINIKUBE_IP}}.nip.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: demo-app-service
              port:
                number: 8080