---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-inject
  namespace: akv-test
spec:
  vault:
    name: k8skeyvault-xIzd # name of key vault
    object:
      name: secret-name    # name of the akv object
      type: secret         # akv object type
