---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akvs-secret-app
  namespace: akv-test
  labels:
    app: akvs-secret-app
spec:
  selector:
    matchLabels:
      app: akvs-secret-app
  template:
    metadata:
      labels:
        app: akvs-secret-app
    spec:
      containers:
      - name: akv2k8s-env-test
        image: spvest/akv2k8s-env-test:2.0.1
        args: ["TEST_SECRET"]
        env:
        - name: TEST_SECRET
          value: "secret-inject@azurekeyvault"  # ref to akvs
                                                # special akv2k8s Env Injector convention
                                                # <azure-key-vault-secret-name>@azurekeyvault to reference
                                                # the AzureKeyVaultSecret secret-inject we created earlier.
                                                # The env-injector will download this secret from Azure Key Vault
                                                # and inject into the executable running in your Container.
        - name: ENV_INJECTOR_LOG_LEVEL
          value: Info                           # supported log levels: Trace, Debug, Info, Warning, Error, Fatal and Panic
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
